config/routes.rb
RcqrsBlog::Application.routes.draw do
  root :to => 'posts#index'

  match 'feed' => 'posts#index', :as => :feed
  match ':year/:month/:day/:slug' => 'posts#show', :as => :post_slug,
    :year => /[0-9]{4}/, :month => /[0-9]{1,2}/, :day => /[0-9]{1,2}/, :slug => /(\w|\-)+/

  resource :submit_comment, :controller => 'submit_comment'
  
  namespace :admin do
    resources :comments

    resource :create_blog, :controller => 'create_blog'
    resource :publish_blog_post, :controller => 'publish_blog_post'
    resource :approve_comment, :controller => 'approve_comment'
  end
  

end

app/models/blog_report.rb
class BlogReport < ActiveRecord::Base
end

app/models/comment_report.rb
class CommentReport < ActiveRecord::Base
  scope :pending, where(:approved_at => nil)
  scope :approved, where('approved_at IS NOT NULL')
  scope :guid, lambda {|guid| where(:guid => guid) }
  scope :for, lambda {|post| where(:post_id => post.guid) }
  
  is_gravtastic!
end

app/models/post_report.rb
class PostReport < ActiveRecord::Base
  scope :published, lambda { where('published_at IS NOT NULL AND published_at <= ?', Time.zone.now) }
  scope :recent, lambda { published.order(:published_at) }
  scope :guid, lambda {|guid| where(:guid => guid) }
  
  def self.by_slug(params)
    published.where(
      :year => params[:year], :month => params[:month], :day => params[:day], :slug => params[:slug]
    ).first or raise ActiveRecord::RecordNotFound
  end
  
  def self.exists?(guid)
    ! where(:guid => guid).empty?
  end
end

app/controllers/admin/admin_controller.rb
module Admin
  class AdminController < ApplicationController
    layout 'admin'
    
    before_filter :ensure_administrator_only
    
  protected
  
    # Prevent non-administrators from accessing these actions
    def ensure_administrator_only
      # TODO
    end
  end
end

app/controllers/admin/approve_comment_controller.rb
module Admin
  class ApproveCommentController < AdminController
    def create
      @command = ApproveCommentCommand.new(params[:command])
      if @command.valid?
        publish(@command)
        
        flash[:notice] = "Comment approved"
      else
        flash[:warning] = "Failed to approve comment. #{@command.errors.full_messages.join(',')}"
      end
      redirect_to admin_comments_path
    end
  end
end

app/controllers/admin/comments_controller.rb
module Admin
  class CommentsController < AdminController
    def index
      @pending = CommentReport.pending
    end
  end
end

app/controllers/admin/create_blog_controller.rb
module Admin
  class CreateBlogController < AdminController
    skip_before_filter :find_blog
    
    def new
      @command = CreateBlogCommand.new
    end
  
    def create
      @command = CreateBlogCommand.new(params[:command])
      if @command.valid?
        publish(@command)
        redirect_to root_path
      else
        render :action => 'new'
      end
    end
  end
end

app/controllers/admin/publish_blog_post_controller.rb
module Admin
  class PublishBlogPostController < AdminController
    def new
      @command = PublishBlogPostCommand.new
    end
  
    def create
      @command = PublishBlogPostCommand.new(params[:command])
      if @command.valid?
        publish(@command)
        redirect_to root_path
      else
        render :action => 'new'
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  attr_reader :blog
  before_filter :find_blog
  
  helper_method :show_post_url
  
protected

  def publish(command)
    Rcqrs::Gateway.publish(command)
  end
  
  # Redirect to create a new blog if none exists
  def find_blog
    @blog ||= BlogReport.first
    redirect_to new_admin_create_blog_path and return false if @blog.nil?
  end
  
  def show_post_url(post, options={})
    options.merge!(:year => post.year, :month => post.month, :day => post.day, :slug => post.slug)
    post_slug_path(options)
  end
end

app/controllers/create_blog_post_controller.rb
class CreateBlogPostController < ApplicationController
  def new
    @command = CreateBlogPostCommand.new
  end
  
  def create
    @command = CreateBlogPostCommand.new(params[:command])
    if @command.valid?
      publish(@command)
      redirect_to root_path
    else
      render :action => 'new'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = PostReport.recent.limit(5)
    
    respond_to do |format|
      format.html
      format.atom
    end
  end
  
  def show
    @post = PostReport.by_slug(params)
    @comments = CommentReport.approved.for(@post)
    @submit_comment_command = SubmitCommentCommand.new(:post_id => @post.guid)
  end
end

app/controllers/submit_comment_controller.rb
class SubmitCommentController < ApplicationController
 def create
    @command = SubmitCommentCommand.new(params[:command])
    if @command.valid?
      publish(@command)
      
      post = PostReport.guid(params[:command][:post_id]).first
      
      flash[:notice] = 'Comment accepted, pending approval'
      redirect_to show_post_url(post)
    else
      render :action => 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_helper
    [:notice, :warning, :message].map { |f| content_tag(:div, flash[f], :class => f) if flash[f] }
  end
end

app/views/admin/approve_comment/_form.html.erb
<%= form_for(command, :url => admin_approve_comment_path, :as => :command) do |f| %>
  <div class="actions">
		<%= f.hidden_field :post_id %>
		<%= f.hidden_field :comment_id %>
    <%= f.submit 'Approve' %>
  </div>
<% end %>

app/views/admin/comments/index.html.erb
<h1>Admin &raquo; Pending Comments</h1>

<% unless @pending.empty? -%>
	<table>
		<thead>
			<tr>
				<th>Author</th>
				<th>Website</th>
				<th>Comment</th>
				<th>In Response To</th>
				<th />
			</tr>
		</thead>
		<tbody>
			<% for comment in @pending -%>
			<tr>
				<td><%= comment.author %><br /><%= mail_to comment.email %></td>
				<td><%= link_to comment.website, comment.website %></td>
				<td><%= comment.comment %></td>
				<td><%= comment.post_title %></td>
				<td>
					<%= render 'admin/approve_comment/form', :command => ApproveCommentCommand.new(:post_id => comment.post_id, :comment_id => comment.guid) %>
				</td>
			</tr>
			<% end -%>
		</tbody>
	</table>
<% else -%>
	<p>There are no comments awaiting moderation.</p>
<% end -%>

app/views/admin/create_blog/_form.html.erb
<%= form_for(@command, :url => admin_create_blog_path, :as => :command) do |f| %>
  <% if @command.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@command.errors.count, "error") %> prohibited this blog from being created:</h2>
    <ul>
    <% @command.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

	<div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

	<div class="field">
    <%= f.label :tagline %><br />
    <%= f.text_field :tagline %>
  </div>
  
  <div class="actions">
    <%= f.submit 'Create' %>
  </div>
<% end %>

app/views/admin/create_blog/new.html.erb
<h1>Create Your Blog</h1>

<%= render 'form' %>

app/views/admin/publish_blog_post/_form.html.erb
<%= form_for(@command, :url => admin_publish_blog_post_path, :as => :command) do |f| %>
  <% if @command.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@command.errors.count, "error") %> prohibited this blog post from being created:</h2>
    <ul>
    <% @command.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

	<div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

	<div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  
  <div class="actions">
    <%= f.submit 'Publish' %>
  </div>

	<p>Uses <a href="http://github.github.com/github-flavored-markdown/">GitHub Flavored Markdown</a> for formatting.</p>
	
	<h2>Live preview</h2> 

	<div class="blogpost">
		<div id="result" class="entry"></div>
	</div>
<% end %>

app/views/admin/publish_blog_post/new.html.erb
<% content_for :head do %>
  <%= javascript_include_tag 'showdown', 'preview' %>
<% end %>

<h1>Admin &raquo; Publish New Blog Post</h1>

<%= render 'form' %>

app/views/create_blog/_form.html.erb
<%= form_for(@command, :url => create_blog_path, :as => :command) do |f| %>
  <% if @command.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@command.errors.count, "error") %> prohibited this blog from being created:</h2>
    <ul>
    <% @command.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

	<div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

	<div class="field">
    <%= f.label :tagline %><br />
    <%= f.text_field :tagline %>
  </div>
  
  <div class="actions">
    <%= f.submit 'Create' %>
  </div>
<% end %>

app/views/create_blog_post/_form.html.erb
<%= form_for(@command, :url => create_blog_post_path, :as => :command) do |f| %>
  <% if @command.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@command.errors.count, "error") %> prohibited this blog from being created:</h2>
    <ul>
    <% @command.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

	<div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

	<div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  
  <div class="actions">
    <%= f.submit 'Create Blog Post' %>
  </div>

	<p>Uses <a href="http://github.github.com/github-flavored-markdown/">GitHub Flavored Markdown</a> for formatting.</p>
	
	<h2>Live preview</h2> 

	<div id="result"></div>
<% end %>

app/views/posts/_comment.html.erb
<li class="comment byuser comment-author-admin bypostauthor even thread-even depth-1 parent" id="comment-16">
	<div id="comment-<%= comment.guid %>" class="comment-body">
		<div class="comment-author vcard">
			<%= image_tag comment.gravatar_url(:size => 32), :class => 'avatar avatar-32 photo', :size => '32' %>			
			<cite class="fn">
				<% unless comment.website.blank? -%>
					<%= link_to comment.author, comment.website %>
				<% else -%>
					<%= comment.author %>
				<% end -%>
				</cite> 
			<span class="says">says:</span>
		</div>
		<div class="comment-meta commentmetadata">
			<%= link_to comment.created_at.to_s(:ordinal), :anchor => "comment-#{comment.guid}" %>
		</div>

		<p><%= comment.comment %></p>
	</div>
</li>

app/views/posts/_post.html.erb
<div class="blogpost">
	<div class="comments">
		<%= link_to post.comment_count, show_post_url(post, :anchor => 'comments') %>
	</div>

	<h2 class="title"><%= link_to post.title, show_post_url(post) %></h2>
	<div class="meta">Published <%= post.published_at.to_s(:ordinal) %> by admin</div>
	<div class="entry">
		<%=raw post.html_content %>
	</div>
</div>

app/views/posts/index.html.erb
<% content_for :head do -%>
	<%= auto_discovery_link_tag(:atom, feed_path(:atom)) %>
<% end -%>

<% content_for :sidebar do -%>
	<!-- <div class="widget widget_categories">
			<h3>Categories</h3>
			<ul>
				<li class="cat-item"><a href="/" title="View all posts filed under Category">Category</a></li>
			</ul>
		</div> -->
<% end -%>

<% for post in @posts -%>
	<%= render 'post', :post => post %>
<% end -%>

<!-- <div class="wp-pagenavi">
	<span class="pages">Page 1 of 6</span>
	<span class="current">1</span>
	<a href="/page/2/" class="page" title="2">2</a>
	<a href="/page/3/" class="page" title="3">3</a>
	<a href="/blog/page/4/" class="page" title="4">4</a>
	<a href="/blog/page/5/" class="page" title="5">5</a>
	<a href="/blog/page/2/" class="nextpostslink">»</a>
	<span class="extend">...</span>
	<a href="/page/6/" class="last" title="Last &raquo;">Last »</a>
</div> -->

app/views/posts/show.html.erb
<%= render 'post', :post => @post %>

<h3 id="comments"><%= pluralize @post.comment_count, 'Responses' %> so far.</h3>

<ol class="commentlist">
	<%= render :partial => 'comment', :collection => @comments %>
</ol>

<%= render 'submit_comment/form', :command => @submit_comment_command %>

app/views/publish_blog_post/_form.html.erb
<%= form_for(@command, :url => publish_blog_post_path, :as => :command) do |f| %>
  <% if @command.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@command.errors.count, "error") %> prohibited this blog post from being created:</h2>
    <ul>
    <% @command.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

	<div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

	<div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  
  <div class="actions">
    <%= f.submit 'Publish' %>
  </div>

	<p>Uses <a href="http://github.github.com/github-flavored-markdown/">GitHub Flavored Markdown</a> for formatting.</p>
	
	<h2>Live preview</h2> 

	<div class="blogpost">
		<div id="result" class="entry"></div>
	</div>
<% end %>

app/views/shared/_actions.html.erb
<div class="widget">
	<h3>Actions</h3>
	<ul>
		<li class="cat-item"><%= link_to 'Publish new blog post', new_admin_publish_blog_post_path %></li>
		<li class="cat-item"><%= link_to 'Comment moderation', admin_comments_path %></li>
	</ul>
</div>

app/views/shared/_footer.html.erb
<div class="footernav">
	<ul>
		<li><%= link_to 'Home', root_path, :title => 'Home page' %></li>
	</ul>
</div>

<div class="copyright">Theme by <a href="http://smashingmagazine.com">SmashingMagazine</a> and <a href="http://slimmity.com">Slimmity</a></div>

app/views/shared/_ie6_hacks.html.erb
<!--[if IE 6]>
	<%= javascript_include_tag 'DD_belatedPNG' %>
	<%= javascript_tag do -%>
		DD_belatedPNG.fix('*');
	<% end -%>
	<%= stylesheet_link_tag 'ie6.css' %>
<![endif]-->

app/views/shared/_page_navigation.html.erb
<ul class="sf-menu sf-js-enabled sf-shadow" id="nav">
	<li class="page_item page-item-3"><a href="<%= url_for root_path %>" title="Home"><cufon class="cufon cufon-canvas" alt="Home" style="width: 52px; height: 18px; "><canvas width="63" height="21" style="width: 63px; height: 21px; top: -3px; left: -1px; "></canvas><cufontext>Home</cufontext></cufon></a></li>
</ul>

app/views/shared/_search.html.erb
<div class="widget widget_search">
	<form method="get" id="sidebarsearch" action="" ><div> 
		<input type="text" value="" name="s" id="keyword" /> 
		<input type="submit" name="submit" id="searchsubmit" value="Search" /></div>
	</form>
</div>

app/views/shared/_subscriptions.html.erb
<div class="widget widget_rssfeed">
	<ul>
		<li class="rss"><%= link_to 'Subscribe to RSS Feed', feed_path(:atom) %></li>
		<!-- <li class="email"><a href="http://feedburner.google.com/fb/a/mailverify?uri=Slimmity&amp;loc=en_US">Subscribe by Email</a></li> -->
		<!-- <li class="twitter"><a href="http://twitter.com/Slimmity">Follow me on Twitter</a></li> -->
	</ul>
</div>

app/views/submit_comment/_form.html.erb
<div id="comment-form">
	<div id="respond">
		<h3>Leave a Reply</h3>
			<div class="cancel-comment-reply">
				<small><a rel="nofollow" id="cancel-comment-reply-link" href="/simplefolio/2009/11/testing-the-theme-elements/#respond" style="display:none;">Click here to cancel reply.</a></small>
			</div>

		<%= form_for(command, :url => submit_comment_path, :as => :command, :html => { :id => 'commentform' }) do |f| %>
			<% if command.errors.any? %>
		  <div id="errorExplanation">
		    <h2><%= pluralize(command.errors.count, "error") %> prohibited this comment from being submitted:</h2>
		    <ul>
		    <% command.errors.full_messages.each do |msg| %>
		      <li><%= msg %></li>
		    <% end %>
		    </ul>
		  </div>
		  <% end %>
	
	    <%= f.text_field :author %>
			<%= f.label :author, raw("Name <small>(required)</small>") %>
			
			<%= f.text_field :email %>
			<%= f.label :email, raw("Mail <small>(required)</small>") %>
			
			<%= f.text_field :website %>
			<%= f.label :website, "Website" %>
			
			<%= f.text_area :comment %>
			
			<%= f.hidden_field :post_id %>
			
			<%= f.submit 'Submit', :id=> 'commentSubmit' %>
		<% end -%>
	</div>
</div>

app/views/submit_comment/new.html.erb
<h1>Submit Comment</h1>

<%= render 'form', :command => @command %>